### ISSUE TITLE
The middleware for Echo looks incompatible with v4.

### ISSUE THREAD

**Issue by yasuflatland-lf** [glassonion1/logz#1]
I tried to use the [echo middleware](https://github.com/glassonion1/logz/tree/main/contrib/github.com/labstack/echo/logzecho), but it may not be compatible with v4. Could you expose the middleware compatible to "github.com/labstack/echo/v4", instead of "github.com/labstack/echo"?

I locally copied the echo middleware switched the import to "github.com/labstack/echo/v4", then it worked. I built my application according to this [sample](https://github.com/labstack/echo#example) at the Echo repo's README.

 I'm new to Go so I may misunderstand, so please close this issue if I understand incorrectly.

**Comment by glassonion1** [comment]
I did not know that V4 was released.
Correct to support V4 as soon as possible.

**Comment by yasuflatland-lf** [comment]
@glassonion1 Sounds good! This logging library is super useful and spot on our needs. I started using this for our projects too. Thank you for creating this library!

**Comment by glassonion1** [comment]
I released logz v0.3.10 just now.
Please check it.
contrib/github.com/labstack/echo/logzecho/v0.3.10

**Comment by yasuflatland-lf** [comment]
@glassonion1 Thank you for your quick update! I'll give it a try!

**Comment by yasuflatland-lf** [comment]
@glassonion1 It worked perfect! Please close this ticket!

**Comment by glassonion1** [comment]
Thank you for confirmation.
Just let me know if you need any improvement.
